# Missing data handling 

The App deal with missing data differently depending on analyses type.    

## Escapement only and S-R data

In those cases, missing data will be ignored.  

## Run data
Missing data in Run data type has multiple sources: 
* Run,Escapement,or Harvest data are missing 
* Run age composition data are missing. 

In either case, this will affect construction of a brood table of multiple years. 
In the following example, missing age data of 1995 will reasult in loosing recruit data of of 1989, 1990, and 1991. 

**Missing 1995 age data  ** 

| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000   | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000   | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000   | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000 | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000   | |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375    | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |1125    | |7532  | |  | |	 | |  | 
|1996  | |1000    | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000    | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|

**Resulting brood table**  
Brood table of 1989,1990, and 1991 data will be deleted. 

| b.Year | |Spawner| |b.Age4 | |b.Age5 | |b.Age6 | |Recruit | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|
| 1988| | 2500    | | 1946    | |3005     | | 0    | | 4951| 
| 1989| | 15000   | | 55896 | |6800 | | | |  | 
| 1990| | 14000   | | 673   | | | | 54| | | 
| 1991| | 2000    | |    | | 2795 | | 0| | | 
| 1992| | 5000    | | 2526 | | 6105| | 78| | 8709| 
| 1993| | 12000   | | 40855  | | 6275| | 4823| | 51953| 
| 1994| | 2375  | | 1569 | | 9110| | 75| | 10754| 
| 1995| | 1125  | | 39118  | | 1411| | 94| |40623    | 
| 1996| | 1000  | | 395  | | 1081 | | 670  | |2146  | 
|______|_|_______|_|_______|_|______|_|______|_|______|

In this case, filling the missing age composition data would be a reasonable remedy. 

On the other hand, when run and escapement data are missing. 

**Missing 1995 data Entirely ** 

| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000   | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000   | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000   | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000 | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000   | |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375    | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |    | |  | |0.23| |0.76	 | |0.01  | 
|1996  | |1000    | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000    | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
  
**Resulting brood table**  
Brood table of 1989,1990,1991,and 1995 data will be deleted. 

| b.Year | |Spawner| |b.Age4 | |b.Age5 | |b.Age6 | |Recruit | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|
| 1988| | 2500    | | 1946    | |3005     | | 0    | | 4951| 
| 1989| | 15000   | | 55896 | |6800 | | | |  | 
| 1990| | 14000   | | 673   | | | | 54| | | 
| 1991| | 2000    | |    | | 2795 | | 0| | | 
| 1992| | 5000    | | 2526 | | 6105| | 78| | 8709| 
| 1993| | 12000   | | 40855  | | 6275| | 4823| | 51953| 
| 1994| | 2375  | | 1569 | | 9110| | 75| | 10754| 
| 1995| |   | | 39118  | | 1411| | 94| |40623    | 
| 1996| | 1000  | | 395  | | 1081 | | 670  | |2146  | 
|______|_|_______|_|_______|_|______|_|______|_|______|


If only age data are missing, it may be reasonable to fill the age. 



**Reduce minor age classes**

Default is making brood table based on all ages.  User can also have an option of set minimum and maximum age with  **Select Run Age** slider.

Minor age classes reduction has two options: 

* Pool option (check **Pool Ages**) : Pool  minor age to next age (e.g. combine ages 3 and 4, and ages 5 and 6)  
* Drop option (uncheck **Pool Ages**): Drop minor age and recalculate proportion (e.g. drop ages 3 and 6)  

**Original age composition**  

| Year | |  Spawner| | Run    | | A3  | |  A4 | | A5  | | A6  | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
|1966  | |1000   | |4500  | | 0.06 | | 0.45 | | 0.43 | |  0.06  |
|1967  | |1200   | |6000  | | 0.03 | | 0.48 | | 0.42 | |  0.07  |
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|

  
  
**Pool Option** 

| Year | |  Spawner| | Run    | | A4  | |  A5 |  
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|
|1966  | |1000   | |4500  | | 0.51 | | 0.49 | 
|1967  | |1200   | |6000  | | 0.51 | | 0.49 | 
|_____|_|_______|_|______|_|_____|_|_____|
**1966:  0.06+0.45 = 0.51   0.43+0.06 = 0.49**  
**1967:  0.03+0.48 = 0.51   0.42+0.07 = 0.49**  


**Drop Option**   

| Year | |  Spawner| | Run    | | A4  | |  A5 |  
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|
|1966  | |1000   | |4500  | | 0.51 | | 0.49 | 
|1967  | |1200   | |6000  | | 0.53 | | 0.47 | 
|_____|_|_______|_|______|_|_____|_|_____|
**1966:  0.45/(0.45+0.43) = 0.51   0.43/(0.45+0.43) = 0.49**  
**1967:  0.48/(0.48+0.42) = 0.53   0.42/(0.48+0.42) = 0.47**  

## State-Space Model    
Running State-Space model requires additional data **CV and efn** 
Additional columns cv_N, cv_E, cv_H, and efn should be entered when running a state-space SR model. 

---

| Year | | ....| | cv_N    | | cv_E  | |  cv_H | | efn  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
|1966  | |.... | |0.27  | | 0.48 | | 0.02 | | 100 |
|1967  | |....  | |0.35  | | 0.49 | | 0.02 | | 100 | 
|1968  | |....  | |0.24  | | 0.37 | | 0.02 | | 100 |
|1969  | |....  | |0.34  | | 0.57 | | 0.02 | | 100 |
|1970  | |....  | |0.49  | | 0.67 | |	0.02 | | 100 | 
|1971  | |.... | |0.33  | | 0.51 | |	0.02 | | 100 |
|1972  | |....   | |0.14  | | 0.54 | |	0.02 | | 100 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|

Generally   
* cv_N: CV of Run size (usually unknown: )
* cv_E: CV of Escapement size (usually large: 0.1 ~ 0.8)
* cv_H: CV of Harvest size (usually small: 0.01 ~ 0.1)
* efn: Effective sample size (usually: 50 - 100)

When run size is estimated by summing Escapement and Harvest: **Run = Escapement + Harvest**, run cv is not available. 
In this case, keep cv_N column blank.  The app will estimate run CV as  
$$run CV = \frac{\sqrt{(eCV\times Esc)^{^{2}}+(hCV\times H)^{^{2}}}}{Run}$$

When Escapement is estimated by subtracting Harvest from Run: **Escapement = Run - Harvest**, escapement cv is not available.   

In this case, keep cv_E column blank.  The app will estimate run CV as  
$$esc CV = \frac{\sqrt{(runCV\times Run)^{^{2}}+(hCV\times H)^{^{2}}}}{Esc}$$

**efn: Effective sample size**
The efn is **NOT** an actual (e.g. scale) sample size to estimate run age composition, but **modeling weights** (i.e.,uncertainties about age composition).  efn of 100 usually indicates 90% CI of +/- 0.1-0.15.  
**efn: Rule of thumb** 
* 100: Default: average confidence   
* <100: Less confident
* >100: Highly confident  

## Trouble shooting and Special cases 

**Don't have complete data**
The app excludes years of missing data (see brood table), and SR analyses will be conducted using complete data set. 


**Want to use Escapement data years before complete run data were collected.**
The input data calculates brood year recruit several ages before the calendar year.  In the above example, a complete brood year starts from **1966**, but brood year recruit data are available starting from **1963**.  When you **DO** have escapement data starting 1963, you arranged the input data by inserting  **Real** escapement and **Dummy** run and age data. 

| Year | |  Spawner| | Run    | | A3  | |  A4 | | A5  | | A6  | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
| 1963 | | 2500  || 3500 | | 0.2  | | 0.2  | | 0.3  | |  0.3   |
| 1964|  | 12000| | 13000 || 0.2  | | 0.2 |  | 0.3 |  |  0.3  |
| 1965 | | 3200  || 3250  || 0.2  | | 0.2  | | 0.3|   |  0.3   |
| 1966|  | 1000 | | 4500  || 0.01 | | 0.45|  | 0.43|  |  0.06  |
| 1967 | | 1200  || 6000|  | 0.03 | | 0.48 | | 0.42 | |  0.07  |
| 1968|  | 2500 | | 8250 | | 0.01 | | 0.42|  | 0.52|  |  0.06  |
| 1969 | | 3500|  | 12500| | 0.05 | | 0.56 | | 0.38|  |  0.01  |
| 1970  || 2000 | |	4000  || 0.01 | |	0.42|	 | 0.52|  |	 0.06  |
| 1971  || 1600 | |	3000  || 0.01  ||	0.42 | | 0.52|  |  0.06  |
| 1972  ||  900  ||	2000  || 0.01|  |	0.42| | 0.52|  |  0.06  |
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|



