---
title: "Escapement goal analysis report"
author:
  - name:
date: '`r format(Sys.time(), "%d %B, %Y")`'
#output: officedown::rdocx_document
output: word_document
reference_docx: template.docx


params:
Tbl_sum: NA
srplot: NA

---

```{r,echo=FALSE,include=FALSE}
knitr::opts_chunk$set(echo = FALSE,comment=NULL, dev='png',fig.dim = c(9,6),dpi=600,message=FALSE,background=NULL)
#opts <- options(knitr.kable.NA = "")
```


```{r,echo = FALSE, fig.cap = paste0("Figure 1.  Spawner-recruit curve (sold line: median, dash mean).  Gray shade indicates ", input$CI,"% Bayesian ",input$Li," interval.")}
srplot()
```


```{r,echo = FALSE, fig.cap = paste0("Figure 2  Spawner-recruit curve (sold line: median, dash mean).  Gray shade indicates ", input$CI,"% Bayesian ",input$Li," interval.")}
yldplot()
```

```{r,echo = FALSE}
#smsy.prof()
#params$Plt_MSY_Prof
cat("Figure 3. MSY Profile Analyses plot. ")
```


```{r,echo = FALSE}
#smax.prof()
#params$Plt_MSR_Prof
cat("Figure 4. Smax Profile Analyses plot. ")
```



```{r,echo = FALSE,eval=(input$dataType=='Run')}
kable(round(brood.out()$brood,0),caption = "Table 1. Input brood table .")
```


```{r,echo = FALSE,fig. }
cat("Table 2.  JAGS Model Summary output.")
print(run.JAGS())
```

```{r,echo = FALSE}
kable(run.JAGS()$summary,caption = "Table. JAGS summary",format="pandoc" ) 
```



```{r,echo = FALSE}
kable(params$Tbl_sum,caption = "Table 3.  Standard Spawner Recruit Analyses summary.  Note: outliers were removed.",format="pandoc" ) 
```



