\newpage
# Methods

### Ricker model 
$$R = \alpha Se^{-\beta S}e^{\varepsilon}$$
**Log-linear form**
$$R = ln.\alpha -\beta S+ln(S) +\varepsilon $$
where $ln.\alpha = ln(\alpha)$, $s_{y} = S_{y}\cdot{10}^{-d}$ and $d = Int(log(\bar{S}))$.   

where 
$$\varepsilon_{iid} \sim N(0,\sigma ^{2})$$
## Model data fitting

In data fitting of the model, recruit ($R_{y}$) derived from the y-th brood year spawner ($S_{y}$) is assumed to be log-normally distributed with mean $\mu_{y}$ and variance ${\sigma}^{2}$
 
$$ln(R_{y}) \sim N(\mu_{y},{\sigma}^{2})$$
where $\mu_{y}$ is a log-linearlized Ricker spawner-recruit model 

$$\mu_{y} = ln.\alpha -\beta s_{y}+ln(S_{y})$$

In the above equations, the conversion from $S$ to $s$ makes $\beta$ to a range similar to the range of $ln.\alpha$.  This is numerically more efficient to estimate parameters. 

## Model priors 
Model priors were set to be uniform (Table 1)

|Parameter |   Prior    |    Note  |
|  ------- | -------:|-------:|
| $ln(\alpha)$  |  $ln(\alpha) \sim U(0,10)$ |  All models   | 
| $\beta$    |     $\beta \sim U(0,10)$  |  All models   | 
| $\sigma$    |      $\sigma \sim U(0,10)$  |  All models    | 
| $\phi$    |    $\phi \sim U(-1,1)$   |  **AR1 option**  | 
| $\varepsilon_{0}$ |     $\varepsilon_{0} \sim N(0,100)$     |**AR1 option**  | 
| $\sigma _{\omega}$|     $\sigma _{\omega} \sim U(0,10)$     |**TVA option**| 

Table 1.  Priors for the Ricer/Beverton-Holt spawner recruit model parameters.


## Model Output Parameters based on expected mean vs. median recruit 

**statistical bias corrected alpha parameters**  
$$ln.\alpha_{c} = ln.\alpha + \frac{\sigma^{2}}{2}$$ 
and $$\alpha_{c} = \alpha e^{\frac{\sigma^{2}}{2}}$$

AR1 model, 
$$ln.\alpha_{c} = ln.\alpha+ \frac{\sigma^{2}}{2(1-\phi^{2})}$$ 

and 
$$\alpha_{c} = \alpha e^{\frac{\sigma^{2}}{2(1-\phi^{2})}}$$
$$Median(R) = \alpha Se^{-\beta S}$$
$$Mean(R) = \alpha_{c} Se^{-\beta S}$$

$$Predicted (R) = \alpha Se^{-\beta S}e^{\sigma}$$
## Biological Reference Parameters
Following biological reference parameters are generated from the model 
* Seq   Spawner abundance expected to produce the same number of recruits
* Smsy  Spawner abundance expected to produce the maximum number of yield (MSY) 
* Umsy  Exploitation rate expected to produce MSY
* Smax  Spawner abundance expected to produce the maximum number of recruits.  
* Sgen  Spawner abundance expected to produce recruitment size of Smsy. Sgen is a conservation benchmark used by Department of Ocean Canada (DFO)

$$S_{eq} =  \frac{ln.\alpha}{\beta}$$
Smsy and Umsy of the Riker model is an approximate where 0 < $ln(\alpha)$ < 3  (Hilbon 1985) 
$$S_{msy} =  S_{eq}(0.5-0.07ln.\alpha)$$
$$U_{msy} =  ln.\alpha(0.5-0.07ln.\alpha)$$
$$S_{max} =  \frac{1}{\beta}$$

**Sgen** is approximated by numerically solving $S$ in following equation
$$ln.\alpha-\beta S_{gen} + ln(S_{gen}) - ln(S_{msy}) = 0$$

**When using lognormal bias corrected model, replace $\alpha$ and $ln(\alpha)$ with $\alpha.c$ and $ln(\alpha.c)$.**


## Outlier removal 

Outlier is defined as posteriors that are below $q_{0.25}-1.5\cdot IQR$ or above $q_{0.75}+1.5\cdot IQR$, where $q_{0.25}$ and $q_{0.75}$ are 25% and 75% percentile or Q1 and Q3, and $IQR$ is the difference between the two. 

The outliers are removed when  
  * beta is negative ( $\beta \le$  0)
  * log-odd ratio of  $ln(0.001\beta/(1-0.001\beta))$  is outlier
  * log-odd ratio of  $ln(0.001ln.\alpha /(1-0.001ln.\alpha))$  is outlier
  
