\newpage
# Methods
## Spawner Recruit Model
The spawner-recruit data are fitted to the **Ricker (1957)** or **Beverton-Holt (1958)** model. 

### Ricker model 
$$R = \alpha Se^{-\beta S}e^{\varepsilon}$$
**Log-linear form**
$$R = ln.\alpha -\beta S+ln(S) +\varepsilon $$
where $ln.\alpha = ln(\alpha)$, $s_{y} = S_{y}\cdot{10}^{-d}$ and $d = Int(log(\bar{S}))$.   


### Beverton-Holt model 
$$R = \frac{\alpha S}{1+\beta S}e^{\varepsilon}$$
**Log-linear form**
$$R=ln.\alpha -ln(1+\beta S)+ln(S) + \varepsilon$$

where 
$$\varepsilon_{iid} \sim N(0,\sigma ^{2})$$
## Model data fitting

In data fitting of the model, recruit ($R_{y}$) derived from the y-th brood year spawner ($S_{y}$) is assumed to be log-normally distributed with mean $\mu_{y}$ and variance ${\sigma}^{2}$
 
$$ln(R_{y}) \sim N(\mu_{y},{\sigma}^{2})$$
where $\mu_{y}$ is a log-linearlized Ricker or Beverton-Holt spawner-recruit model 

**Ricker Model**
$$\mu_{y} = ln.\alpha -\beta s_{y}+ln(S_{y})$$
**Beverton-Holt Model**
$$\mu_{y}=ln.\alpha -ln(1+\beta s_{y})+ln(S_{y})$$
where $ln.\alpha = ln(\alpha)$, $s_{y} = S_{y}\cdot{10}^{-d}$ and $d = Int(log(\bar{S}))$.   


In the above equations, the conversion from $S$ to $s$ makes $\beta$ to a range similar to the range of $ln.\alpha$.  This is numerically more efficient to estimate parameters. 

### Additional Model options 

#### AR(1) model option 
AR(1) model (First-order autoregressive model) assumes that the residual is serially auto correlated or that the value of residual at time *y* is a linear function of the residual at time *y-1*.  

This is modeled as 

$${\varepsilon_{y}}=\phi {\varepsilon_{y-1}}+{\nu_{y}}$$
where 
$${\nu_{y}} \sim N(0,{\sigma _{\nu }}^{2})$$

#### Time variant alpha model option  
Time variant alpha model assumes that alpha takes random walk process. 

$${ln.\alpha_{y}}={ln.\alpha_{y-1}}+{\omega_{y}}$$
where 
$${\omega_{y}} \sim N(0,{\sigma _{\omega }}^{2})$$

## Model priors 
Model priors were set to be uniform (Table 1)

|Parameter |   Prior    |    Note  |
|  ------- | -------:|-------:|
| $ln(\alpha)$  |  $ln(\alpha) \sim U(0,10)$ |  All models   | 
| $\beta$    |     $\beta \sim U(0,10)$  |  All models   | 
| $\sigma$    |      $\sigma \sim U(0,10)$  |  All models    | 
| $\phi$    |    $\phi \sim N(0,0.5)$   |  **AR1 option**  | 
| $\varepsilon_{0}$ |     $\varepsilon_{0} \sim N(0,100)$     |**AR1 option**  | 
| $\sigma _{\omega}$|     $\sigma _{\omega} \sim U(0,10)$     |**TVA option**| 

Table 1.  Priors for the Ricer/Beverton-Holt spawner recruit model parameters.


                                                                      
## Model Output Parameters based on expected mean vs. median recruit 

**statistical bias corrected alpha parameters**  
$$ln(\alpha_{c}) = ln(\alpha) + \frac{\sigma^{2}}{2}$$ 
and $$\alpha.c = \alpha e^{\frac{\sigma^{2}}{2}}$$


AR1 model, 
$$ln(\alpha_{c}) = ln(\alpha)+ \frac{\sigma^{2}}{2(1-\phi^{2})}$$ 
and 
$$\alpha_{c} = \alpha e^{\frac{\sigma^{2}}{2(1-\phi^{2})}}$$

**Ricker model**
$$Median(R) = \alpha Se^{-\beta S}$$
$$Mean(R) = \alpha_{c} Se^{-\beta S}$$

$$Predicted (R) = \alpha Se^{-\beta S}e^{\sigma}$$
**Beverton-Holt model** 
$$Median(R) = \frac{\alpha S}{1+\beta S}$$
$$Mean(R) = \frac{\alpha_{c} S}{1+\beta S}$$
$$Predicted(R) = \frac{\alpha S}{1+\beta S}e^{\sigma}$$

## Biological Reference Parameters
Following biological reference parameters are generated from the model 
* Seq   Spawner abundance expected to produce the same number of recruits
* Smsy  Spawner abundance expected to produce the maximum number of yield (MSY) 
* Umsy  Exploitation rate expected to produce MSY
* Smax  Spawner abundance expected to produce the maximum number of recruits.  
* Sgen  Spawner abundance expected to produce recruitment size of Smsy. Sgen is a conservation benchmark used by Department of Ocean Canada (DFO)

### Ricker model 
$$S_{eq} =  \frac{ln.\alpha}{\beta}$$
Smsy and Umsy of the Riker model is an approximate where 0 < $ln(\alpha)$ < 3  (Hilbon 1985) 
$$S_{msy} =  S_{eq}(0.5-0.07ln.\alpha)$$
$$U_{msy} =  ln.\alpha(0.5-0.07ln.\alpha)$$
$$S_{max} =  \frac{1}{\beta}$$
Note: Smax does not practically exist when $ln.\alpha < 1$.

**Sgen** is approximated by numerically solving $S$ in following equation
$$ln.\alpha-\beta S_{gen} + ln(S_{gen}) - ln(S_{msy}) = 0$$


### Beverton-Holt model
$$S_{eq} =  \frac{\alpha -1}{\beta}$$

$$S_{msy} =  \frac{\sqrt{\alpha} -1}{\beta}$$

$$U_{msy} = 1- \sqrt{\frac{1}{\alpha}}$$

**Beverton-Holt model does not have Smax**
$$S_{max} = NA$$

**Sgen** is approximated by numerically solving $S$ in following equation  

$$ln.\alpha - ln(1+\beta S_{gen}) + ln(S_{gen}) - ln(S_{msy}) = 0$$

**When using lognormal bias corrected model, replace $\alpha$ and $ln(\alpha)$ with $\alpha.c$ and $ln(\alpha.c)$.**


## Outlier removal 

Outlier is defined as posteriors that are below $q_{0.25}-1.5\cdot IQR$ or above $q_{0.75}+1.5\cdot IQR$, where $q_{0.25}$ and $q_{0.75}$ are 25% and 75% percentile or Q1 and Q3, and $IQR$ is the difference between the two. 

The outliers are removed when  
  * beta is negative ( $\beta \le$  0)
  * log-odd ratio of  $ln(0.001\beta/(1-0.001\beta))$  is outlier
  * log-odd ratio of  $ln(0.001ln.\alpha /(1-0.001ln.\alpha))$  is outlier
  


## Profile Analyses

### MSY-RMAX Profile Analysis




**Note** 
  * The RMAx is the Ricker SR model only. RMAX does not exist in the Beverton-Holt SR model. 
  * The when ln.alpha or ln.alpha.c is less than 1.0, Smax (spawner size that produces RMAS) will be **greater** than Seq 


The MSY-RMAX profiles at given range of $S$ was calculated with following steps. 

* In each posterior sample of SR parameters (j) and a given range of spawners $(S_{i} : i = 1,2,... i,..n)$
  * Calculate the model predicted yield $(Y_{i,j})$ or recruit $(R_{i,j})$.
  * For each posterior (j) find the maximum yield (**MSY**) $Max(Y_{j})$ or recruit (**RMAX**) $Max(R_{j})$.
  * Assign $X_{i,j}$ to 1 if the expected yield or recruit is above the q% of the MSY or RMAX
  * Assign $X_{i,j}$ to 0 if otherwise
  * At each $(S_{i})$, calculate the mean of $X_{i,j}$ across the simulation samples (j) that is $(P(S_{i}))$ 
  * $P(S_{i})$ is the probability of a given spawner size ($S_{i}$) producing a mean/median yield or recruit above the q.MSY or q.RMax.   


This is written as: 
$$P(S_{i}) =\frac{\sum_{j=1}^{n}X_{i,j}}{n}$$
where
$$
X_{i,j} = 
\begin{cases}
 1   & \quad\ Y_{i,j}\geq  q\cdot\ Max(Y_{j})\\
 0   & \quad\ otherwise
 \end{cases}
$$
and 
$$
X_{i,j} = 
\begin{cases}
 1   & \quad\ R_{i,j}\geq  q\cdot\ Max(R_{j})\\
 0   & \quad\ otherwise
 \end{cases}
$$
**MSY and RMAX profile based Escapement Goal range**

The MSY and RMAX profile based Escapement Goal range is determined by setting a target achievement probability (p) and deriving a range of S ($S_{l},S_{u}$) where P(S) is equal to and greater than the target p. 

$$\left \{ S_{msy}\leftarrow \left [ S_{l}\: ,\:S_{u}  \right ]|P(S)\geq p \right \}$$
$$\left \{ S_{max}\leftarrow \left [ S_{l}\: ,\:S_{u}  \right ]|P(S)\geq p \right \}$$


### Target Yield-Recruit Profile Analysis


Similar to the MSY and RMAX rpofile analyses, target Yield-Recruit profile at given range of $S$ was calculated with following steps. 

* In each posterior sample of SR parameters (j) and a given range of spawners $$(S_{i} where i = 1,2,... i,...)$$
  * Calculate the model predicted yield $(Y_{i,j})$ or recruit $(R_{i,j})$.
  * Assign $X_{i,j}$ to 1 if the expected yield or recruit is above the target yield (TY) or recruit (TR)
  * Assign $X_{i,j}$ to 0 if otherwise
  * At each $(S_{i})$, calculate the mean of $X_{i,j}$ across the simulation samples (j) that is $(P(S_{i})$ 
  * $(P(S_{i})$ is the probability of a given spawner size ($S_{i}$) producing a yield or recruit above the TY or TR.
  
$$
X_{i,j} = 
\begin{cases}
 1   & \quad\ Y_{i,j}\geq  TY\\
 0   & \quad\ otherwise
 \end{cases}
$$
or 
$$
X_{i,j} = 
\begin{cases}
 1   & \quad\ R_{i,j}\geq  TR\\
 0   & \quad\ otherwise
 \end{cases}
$$
  
  
  
**Target Yield-Recruit based Escapement Goal range**

The target yield and recruit  profile based Escapement Goal range is determined by setting a target achievement probability (p) and deriving a range of S ($S_{l},S_{u}$) where P(S) is equal to and greater than the target p. 


### Custom Escapement Goal Analyses

In the Custom Escapement Goal Analyses, the user defined escapement range(S) was divided to 200 sequence of S ($(S_{1},S_{2},...,S_{i},...S_{200})$). The expected and predicted yield and recruit were calculated for each S for each posterior sample (j), and summarized. 

The probability of yield above the target yield (TY) over the S range was calculated as: 
$$P(Y \geq TY) =\frac{\sum_{i=1}^{200}\sum_{j=1}^{n}X_{i,j}}{200\cdot\ n}$$
$$P(R \geq TR) =\frac{\sum_{i=1}^{200}\sum_{j=1}^{n}X_{i,j}}{200\cdot\ n}$$
