#'===============================================================================
# MSE_functions.R
# Management Strategy Evaluation simulation function 
# MSE.sim  
# This function run MSE : Input data
# srmodel: SR model used to estimate SR parameters
# nyrs: number of simulation (management) years: default 50
# lnalpha.i:  SR lnalpha, beta: SR beta from model
# S0: Actual recent observed escapement that were not used for SR analyses
# e.Rec: Annual recruitment deviation   
# First years of recruits and run are generated by actual observed escapement 
#'===============================================================================

#'------------------------------------------------------------------------------
# Fishery opening trigger-----
# FTA
#'------------------------------------------------------------------------------ 
# Low: Fishery opens when expected run exceeds lower goal
# Middle: Fishery opens when expected run exceeds Mid goal points 
# Upper:  Fishery opens when expected run exceeds Upper goal 
FTA <-function(cmode,LEG,UEG){
  FT <- ifelse(
    cmode =='Middle', mean(c(LEG,UEG)), # Fishery target: mid EG range 
    ifelse(cmode =='Upper',UEG, # Fishery target: Upper EG range 
           LEG # Fishery target lower EG range}       
    ))
  return(FT)
}
# Low: Fishery opens when expected run exceeds lower goal
# Middle: Fishery opens when expected run exceeds Mid goal points 
# Upper:  Fishery opens when expected run exceeds Upper goal 

#'------------------------------------------------------------------------------
# Harvest Control -----
# H.control  
# Fishing mortality based goal.  
#'------------------------------------------------------------------------------ 
H.control <-function(Npred,MSP,FMIN,FMSY,ABCP){
  # Calculate FABC 
  FABC <- ABCP*FMSY
  # Calculate Smsy 
  Smsy <- Npred*(1-FMSY)
  # Calculate MSST
  MSST <- MSSTP*Smsy
  # NL: Critical low abundance
  NL <- MSST/(1-FMIN)
  #  Catch <- ifelse(
  # Case 1: Npred < MSST 
  #    Npred < NL, FMIN,
  #    # Case 2: Npred > MSST 
  #    ifelse(,,),
  #    )
}
#'-------------------------------------------------------------------------------
#  MSE.sim function
#'  Input 
#'  srmodel: Spawner Recruit model
#'  lnalpha.i: annual SR model lnalpha,  beta: annual SR model beta
#'  S0: Starting Spawner by age.
#'  D: SR model D
#'  e.Rec: Annual recruitment deviation
#'  e.p: Expected maturity schedule (broog age comp) 
#'  e.Pred: Annual Prediction deviation 
#'  e.imp:  Annual management implementation deviation
#'  FT:  Fishery Target    
#'  mH:  Minimum harvest 
#'-------------------------------------------------------------------------------  

MSE.sim <- function(srmodel,lnalpha.i,beta,S0,D,e.Rec,e.p,e.pred,e.imp,FT,mH,maxHR){
#'-------------------------------------------------------------------------------
#  Create Brood Ages 
#'-------------------------------------------------------------------------------  
# lage: last age, nages: number of adult return age, fage: first adult return age
  lage <- length(S0)
  nages <- dim(e.p)[2]
  fage <- lage - nages + 1 # first age 
  nyrs <- length(e.pred)
#-------------------------------------------------------------------------------
#  Create Empty vector for simulation and output  
#-------------------------------------------------------------------------------  
# Brood Year Recruit: R0: straight from the model, R: R0 with error 
  R0 <- numeric(nyrs+lage)
  R <- numeric(nyrs+lage)
  # Annual Run: N: True Run , N.pred: Predicted Run: Assessed run with error 
  N <- numeric(nyrs)
  N.pred <- numeric(nyrs)
  # Annual Run by age 
  N.ta <- matrix(0,ncol=nages, nrow=nyrs+lage*2)
  # Annual Harvest: H: True , H.target: Target Harvest 
  H <- numeric(nyrs)
  H.target <-numeric(nyrs)
  # Annual Escapement: S: True   
  S <- numeric(nyrs)
  # EG: Met lower escapement goal?   
  EG <- numeric(nyrs)
  #-------------------------------------------------------------------------------
  #  Population Dynamics: Initialization (b.y is brood year)
  #-------------------------------------------------------------------------------
  for (b.y in 1:lage){
    # Calculate expected Returns from SR model parameter   
    R0[b.y] <- srmodel(lnalpha.i[b.y],beta,S0[b.y],D)
    # Add Error   
    R[b.y] <- R0[b.y]*exp(e.Rec[b.y])
    # Distribute recruitment based on maturity schedule 
    #b.y+fage+a-1 is calendar year. 
    # Example: fage = 4: fish return as age 4.  
    # Fish spawn in b.y (say 2000) will return in 
    # 2004 as 4 years old, 2005 as 5yo, 2006 as 6 yo,...
    for (a in 1:nages){N.ta[b.y+fage+a-1,a] <- R[b.y]*e.p[b.y,a]}
  }  # Expected return   
  
  #-------------------------------------------------------------------------------
  #  Population Dynamics: Management Strategies (y is calendar year) 
  #-------------------------------------------------------------------------------
  for (y in 1:nyrs){
    # Brood year b.y is y + lage
    b.y <-y+lage
    # Annual Run is sum of all ages
    N[y] <- sum(N.ta[b.y,])
    # Predicted Run with error 
    N.pred[y] <- N[y]*(e.pred[y])
    
    # Harvest Target----------------------------------------------------------------
    PY <- N.pred[y] - FT   # Predicted Yield  
  H.target[y] <- ifelse(
      # Case 1: Predicted Yield is negative: Fishery target is minimum harvest
      PY < 0, mH[1], 
      # Case 2: Predicted Yield is positive: 
      # fishery target is surplus or min harvest whichever bigger  
      # fishery target is also between surplus and the max harvest (fishing capacity) whichever smaller 
      min(mH[2],max(mH[1],(N.pred[y]-FT)))
    )  # End ifelse 
    # Target Harvest rate 
    # Set Target harvest rate 
    HTR <- H.target[y]*(e.imp[y])/N.pred[y]
    #  Actual Harvest: Harvest will not exceed of incoming run
    H[y] <- N[y]*min(HTR,maxHR/100)
    S[y] <- N[y] - H[y]
    #     
    R0[b.y] <- srmodel(lnalpha.i[b.y],beta,S[y],D)
    # Expected return        
    R[b.y] <- R0[b.y]*exp(e.Rec[b.y])
    # Fill ages       
    for (a in 1:nages){N.ta[b.y+fage+a-1,a] <- R[b.y]*e.p[b.y,a]}
  }
  #  out <- list(R=data.frame(cbind(N,S,H,R[-c(1:lage)],R0[-c(1:lage)],EG)), N.ta=data.frame(N.ta))
  out <- data.frame(cbind(N,S,H,R[-c(1:lage)]))
  names(out) <- c('N','S','H','R')
  return(out)
}



MSE.sim2 <- function(srmodel,lnalpha.i,beta,S0,D,e.Rec,e.p,e.pred,e.imp,LEG,UEG,cmode){
  #-------------------------------------------------------------------------------
  #  Create Ages 
  #-------------------------------------------------------------------------------  
  # lage: last age, nages: number of adult return age, fage: first adult return age
  lage <- length(S0)
  nages <- dim(e.p)[2]
  fage <- lage - nages + 1
  nyrs <- length(e.pred)
  #-------------------------------------------------------------------------------
  #  Create Empty vector for simulation and outputs  
  #-------------------------------------------------------------------------------  
  # Recruit: R0: straight from model, R: R0 with error 
  R0 <- numeric(nyrs+lage)
  R <- numeric(nyrs+lage)
  # Annual Run (N), Escapement (S), Harvest (H)
  N <- numeric(nyrs)
  S <- numeric(nyrs)
  H <- numeric(nyrs)
  # EG: Met lower escapement goal?   
  EG <- numeric(nyrs)
  # Annual Run by age 
  N.ta <- matrix(0,ncol=nages, nrow=nyrs+lage*2)
  
#-------------------------------------------------------------------------------
#  Population Dynamics: Initialization : Create inital Run based on observed spawner size 
#-------------------------------------------------------------------------------
  for (b.y in 1:lage){
    # Calculate expected Recruit from SR model parameter   
    R0[b.y] <- srmodel(lnalpha.i[b.y],beta,S0[b.y],D)
    # With error   
    R[b.y] <- R0[b.y]*exp(e.Rec[b.y])
    # Distribute recruitment to each year
    for (a in 1:nages){N.ta[b.y+fage+a-1,a] <- R[b.y]*e.p[b.y,a]}
  }  # Expected return      
  
#-------------------------------------------------------------------------------
#  Population Dynamics: Start Management Strategies  
#-------------------------------------------------------------------------------
  for (y in 1:nyrs){
    # Brood year b.y is y + lage
    b.y <-y+lage
    # Annual Run is sum of all ages
    N[y] <- sum(N.ta[b.y,]) 
    # Predicted Run with normal error 
    N.pred <- N[y]*e.pred[y]  
    # Management based on Escapement goal 
    H.target <- ifelse(
      # If projected run is less than FT, Fishery is closed       
      N.pred < FT,0,  
      # If projected run is greater than FT, 
      # Fishery target is max harvest rate of surplus, or max harvest capacity    
      min(input$maxH,(N.pred-FT)*input$maxHr))
    # Actual Harvest: Harvest will not exceed N
    H[y] <- min(H.target*e.imp[y]/N.pred, 0.9)*N[y]
    S[y] <- N[y] - H[y]
    # Escapement goal achievement 
    EG[y] <- ifelse(S[y]>input$LEG,1,0)
    R0[b.y] <- srmodel(lnalpha.i[b.y],beta,S[y],D)
    # Expected return        
    R[b.y] <- R0[b.y]*exp(e.Rec[b.y])
    # Fill ages       
    for (a in 1:nages){N.ta[b.y+fage+a-1,a] <- R[b.y]*e.p[b.y,a]}
  }
  
  out <- data.frame(cbind(N,S,H,EG))
  #  out <- data.frame(N.ta)
  return(out)
}

