
### Running Management Strategy Evaluation (MSE)Analyses  

The escapement goal range analyses are often based on long-term average.  However, those analyses do not evaluate how the goal will be achieved, or probability of achieving the goal range and other management target. In real fishery management, escapement goal may not be achieved due to various factors, too few or too many fish returned to the river, and errors in run assessment (overestimate or underestimate) and fishery execution (fished too much or too few). Even when escapement is within the goal range, future returning run size will vary.

Management Strategy Evaluation (MSE) Analyses is designed to evaluate performance of an escapement goal range in more realistic way.  The simulation model 1) evaluates incoming run size, 2) execute fishery based on predefined escapement goal range and fishery strategy, 3) produce future returns coming from the realized escapement.  

---
**Model Running Steps**    
* **Escapement Goal :** Enter the lower and the upper goal range 
* **Fishery Harvest :**  Enter the minimum and the maximum harvest limit. 
* **Target Escapement:**  Select Lower, Middle, Upper escapement goal
* **Management Priority:**  Select Escapement, Harvest, Hybrid. 
* **Click Simulate** Wait until Trace plots show up.  
* Optional setting 
* **Run Assessment Error:** Precision of run assessment is to determine harvest?  
* **Management Error:** Precision of fishery execution. 


---
**Management Strategy Evaluation Analyses**  
Management Strategy Evaluation (MSE) Analyses is a closed feedback loop simulation model analysis.The model has two components:(1) salmon population dynamic model based on SR model derived from the SR analyses, and (2) fishery management model that conducts fishery and escapement.   The escapement determined by the fishery management model will determine future population dynamics and fishery management, and thus the model is a closed feedback loop.  
**NOTE***  
This simulation assumes no changes in escapement goal range and fishery management strategy 

### MSE Simulation Steps
1.  (**N:**) Fish returns to the river 
2.  (**N':**) Run size is assessed with **error** (Assessment Error)
3.  (**H':**)Harvest limit is set based on the predicted run size 
4.  (**H:**) Fishery is executed with **error** (Execution Error) 
5.  (**S:**) Escapement is a true run(1) minus true harvest(4) 
6.  (**R:**)The brood year return is produced from the escapement and SR model with **error** (Process Error)

**Calendar Year Return**
Run size of calendar year (y) is generated from the brood year returns of from y-a to y-b years, where a and b are the minimum and the maximum return age.    
$$N_{y}=\sum_{i=a}^{i=b}\left ( R_{y-i}\cdot P_{i,y-i} \right )$$
where $P_{i,y}$ is a maturity schedule (i.e., the proportion of i-th age fish returning in brood year y) 

**Assessed Run** 
Assessed run in year (y) is a normal distribution 
$$N'_{y} = N_{y} + \varepsilon$$
where 
$$\varepsilon_{iid} \sim N(0,\sigma ^{2})$$
**Proposed Harvest and Harvest Rate**  
Proposed harvest (H') is based on harvesting criterion function based on assessed run (N')
$$H'_{y} = f(N'_{y})$$
Proposed harvest rate (HR') is a fraction of proposed harvest divided by assessed run.
$$HR'_{y} = H'_{y}/N'_{y}$$

**Realized Harvest**  
Actual harvest is Run  multiplied by proposed harvest with error
$$H_{y} = N_{y}(HR'_{y} + \varepsilon_{h})$$
where 
$$\varepsilon_{h} \sim N(0,\sigma_{h} ^{2})$$
**Escapement**  
Escapement (S) is Run minus realized harvest (H)
$$S_{y} = N_{y} - H_{y}$$
**Future Brood Year Return**
Brood year return (R) is generated from SR model as 
$$R_{y} = SR(S_{y})e^{\varepsilon_{r}}$$
where 
$$\varepsilon_{r} \sim N(0,\sigma_{r} ^{2})$$
SR model and $\varepsilon_{r}$ are derived directly from the model analyses: Ricker, Beverton-Holt SR model with/without AR(1) or TVA. 

**Future Calendar Year Return**
The recruits from the  year (y) of i-th age will return in y+i th year   
$$N_{y+i,i}=R_{y}\cdot P_{i,y}$$
where $P_{i,y}$ is a maturity schedule: the proportion y-th year recruits returning as i-th age in y+i-th year. 

### Fishery Management Strategy  
Fishery salmon fishery management strategy consists of **Escapement Goal** and **Harvest Goal***  

**Escapement Priority**
Escapement priority strategy attempts to meet escapement to the predefined goal range (between lower and upper range). Under this strategy, fishery occurs when an assessed run size exceeds the target escapement (lower,middle, or upper of the escapement goal range).  A proposed harvest rate is (assessed run - target escapement)/(assessed run). This assumes that fishery can harvest ALL surplus (i.e., unlimited fishery capacity). When surplus exceeds the maximum harvest, the proposed harvest rate is (the maximum harvest)/(assessed run).


**Harvest Priority**
Harvest priority strategy attempts to set meet target determined in preseason. Under this strategy harvest target is set  
as proposed harvest is set as: Target Harvest = Preseason run - Target escapement. During the season  

**Hybrid Strategy**
Hybrid strategy follows escapement goal strategy with the very **low** minimum harvest target.  When assessed surplus (i.e. assessed run - target escapement) is below the minimum harvest target, the proposed harvest rate is (minimum target harvest)/(assessed run). 

**Setting Error Range**
In MSE analysis, the following two errors are considered. 
**Run Assessment Error:** Precision of run assessment is to determine harvest?  
**Management Error:** Precision of fishery execution (How similar harvest is between expected and actual?)

Setting an appropriate error range depends clearly on how fisheries management is executed. For instance,**pre-season** **Run Assessment Error** is generally high (+/- 30%), but if execution of fishery is based on **in-season** assessment, then **Run Assessment Error** would be smaller (+/- 5-10%). Similarly,  when management is based on**in-season** assessment of harvest target, **Management Error** would be low (+/- 1-5%).  But, when management is based on fishery opening the error could be high (+/- 10%) (i.e. more/less fishermen participated in the fishery). 






