# Biological Reference Parameters

Following biological reference points are generated from the model 
* Seq   Spawner abundance expected to produce the same number of recruits
* Smsy  Spawner abundance expected to produce the maximum number of yield (MSY) 
* Umsy  Exploitation rate at Rmax that is expected to produce MSY
* Smax  Spawner abundance expected to produce the maximum number of recruits.  
* Sgen  Spawner abundance expected to produce recruitment size of Smsy. Sgen is a conservation benchmark used by Department of Ocean Canada (DFO)

**Ricker model** 
Seq  
$$S_{eq} =  \frac{ln.\alpha}{\beta}$$
Smsy and Umsy of the Ricker model (Scheuerell  2016)
$$S_{msy} =  \frac{1-W(e^{1-ln.\alpha})}{\beta}$$
$$U_{msy} =  1-W(e^{1-ln.\alpha})$$
$$S_{max} =  \frac{1}{\beta}$$
Note: Smax does not **practically** exist when ln.alpha or ln.alpha.c is less than 1.0. This is because the Smax (spawner size that produces RMAX) will be **greater** than Seq 

**Sgen** is approximated by numerically solving $S$ in following equation
$$ln.\alpha-\beta S_{gen} + ln(S_{gen}) - ln(S_{msy}) = 0$$


**Beverton-Holt model** 
$$S_{eq} =  \frac{\alpha -1}{\beta}$$
$$S_{msy} =  \frac{\sqrt{\alpha} -1}{\beta}$$
$$U_{msy} = 1- \sqrt{\frac{1}{\alpha}}$$
**Beverton-Holt model does not have Smax**
$$S_{max} = NA$$

**Sgen** is approximated by numerically solving $S$ in following equation  



**When using lognormal bias corrected model,replace $ln.\alpha$ with $ln.\alpha_{c}$ **
