# Run data type 

Analyses methods available for this data type are: 
* SR Analyses : **Ordinary** and **State-Space** 
* Escapement Goal Analyses 
* MSE (Management Strategy Evaluation) Analyses 

Run data type consists of **Calendar Year**, Spawner (Escapement) size, Run size, and run or run proportion by age.  Age notation should be either run age, starting "A" (A3),or European scale age fw age.sw age starting from "a" (a1.1).  Run age is freshwater + saltwater scale age +1.  For example, run age of scale age 1.1 = 3. 


**Run input table example** 

| Year | |  Spawner| | Run    | | A3  | |  A4 | | A5  | | A6  | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
|1966  | |1000   | |4500  | | 0.06 | | 0.45 | | 0.43 | |  0.06  |
|1967  | |1200   | |6000  | | 0.03 | | 0.48 | | 0.42 | |  0.07  |
|1968  | |2500   | |8250  | | 0.01 | | 0.42 | | 0.52 | |  0.06  |
|1969  | |3500   | |12500 | | 0.05 | | 0.56 | | 0.38 | |  0.01  |
|1970  | |2000   | |4000  | | 0.01 | |	0.42 | | 0.52 | |	 0.06  |
|1971  | |1600   | |3000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1972  | |900    | |2000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1973  | |2000   | |4000  | | 0.01 | |	0.42 | | 0.52 | |	 0.06  |
|1974  | |1600   | |3000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1975  | |900    | |2000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
  
or 


| Year | |  Spawner| | Run    | | a1.1  | |  a1.2 | | a1.3  | | a1.4  | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
|1966  | |1000   | |4500  | | 0.06 | | 0.45 | | 0.43 | |  0.06  |
|1967  | |1200   | |6000  | | 0.03 | | 0.48 | | 0.42 | |  0.07  |
|1968  | |2500   | |8250  | | 0.01 | | 0.42 | | 0.52 | |  0.06  |
|1969  | |3500   | |12500 | | 0.05 | | 0.56 | | 0.38 | |  0.01  |
|1970  | |2000   | |4000  | | 0.01 | |	0.42 | | 0.52 | |	 0.06  |
|1971  | |1600   | |3000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1972  | |900    | |2000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1973  | |2000   | |4000  | | 0.01 | |	0.42 | | 0.52 | |	 0.06  |
|1974  | |1600   | |3000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1975  | |900    | |2000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|

---

From the input table, the app creates a brood table starting the first calendar year's escapement and brood year recruitment.  Final input data will elimitnate any rows with missing data 

| b.Year | |Spawner| |b.Age3 | |b.Age4 | |b.Age5 | |b.Age6 | |Recruit| 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|
| 1959| |       | |     | |     | |     | | 270| |        |
| 1961| |       | |     | |     | | 1935| | 420| |        |
| 1962| |       | |     | | 2025| | 2520| | 495| |        |
| 1963| |       | | 45  | | 2880| | 4290| | 125| | 7340   |
| 1964| |       | | 180 | | 3465| | 4750| | 240| | 8615   |
| 1965| |       | | 83  | | 7000| | 2080| | 180| | 9343   |
| 1966| | 1000  | | 625 | | 1680| | 1560| | 120| | 3985   |
| 1967| | 1200  | | 40  | | 1260| | 1040| | 240| | 2480   |
| 1968| | 2500  | | 30  | | 840 | | 2080| | 180| | 3130   |
| 1969| | 3500  | | 20  | | 1680| | 1560| | 120| | 3380   |
| 1970| | 2000  | |	40  | | 1260| |	1040| |    | |	      |
| 1971| | 1600  | |	30  | | 840 | |	    | |    | |        |
| 1972| |  900  | |	20  | |     | |	    |	|    | |        |
|1973 | |2000   | |  | |  | |	 | |  | |	   |
|1974 | |1600   | |  | | | |	 | |  | |    |
|1975 | |900    | |  | |  | |	 | |  | |    |
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|
---

**Model input data**

| b.Year | |Spawner| |b.Age3 | |b.Age4 | |b.Age5 | |b.Age6 | |Recruit| 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|
| 1966| | 1000  | | 625 | | 1680| | 1560| | 120| | 3985   |
| 1967| | 1200  | | 40  | | 1260| | 1040| | 240| | 2480   |
| 1968| | 2500  | | 30  | | 840 | | 2080| | 180| | 3130   |
| 1969| | 3500  | | 20  | | 1680| | 1560| | 120| | 3380   |
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|


## Special cases

**Want to use Escapement data years before complete run data were collected.**
The input data calculates brood year recruit several ages before the calendar year.  In the above example, a complete brood year starts from **1966**, but brood year recruit data are available starting from **1963**.   Ordinary the 1963-1965 recruit data are unused (because no escapement data.)
When you **DO** have escapement data starting 1963 (but not run data),  you can use the escapement by manipulating input data:  Input **Real** escapement with**Dummy** run and age data. 

| Year | |  Spawner| | Run    | | A3  | |  A4 | | A5  | | A6  | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
| 1963 | | 2500  || 1000 | | 0.2  | | 0.2  | | 0.3  | |  0.3   |
| 1964|  | 12000| | 1000 || 0.2  | | 0.2 |  | 0.3 |  |  0.3  |
| 1965 | | 3200  || 1000  || 0.2  | | 0.2  | | 0.3|   |  0.3   |
| 1966|  | 1000 | | 4500  || 0.01 | | 0.45|  | 0.43|  |  0.06  |
| 1967 | | 1200  || 6000|  | 0.03 | | 0.48 | | 0.42 | |  0.07  |
| 1968|  | 2500 | | 8250 | | 0.01 | | 0.42|  | 0.52|  |  0.06  |
| 1969 | | 3500|  | 12500| | 0.05 | | 0.56 | | 0.38|  |  0.01  |
| 1970  || 2000 | |	4000  || 0.01 | |	0.42|	 | 0.52|  |	 0.06  |
| 1971  || 1600 | |	3000  || 0.01  ||	0.42 | | 0.52|  |  0.06  |
| 1972  ||  900  ||	2000  || 0.01|  |	0.42| | 0.52|  |  0.06  |
|1973  | |2000   | |4000  | | 0.01 | |	0.42 | | 0.52 | |	 0.06  |
|1974  | |1600   | |3000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|1975  | |900    | |2000  | | 0.01 | |	0.42 | | 0.52 | |  0.06  |
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
---
The above will create brood table 


| b.Year | |Spawner| |b.Age3 | |b.Age4 | |b.Age5 | |b.Age6 | |Recruit| 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|
| 1959| |       | | 200 | | 200 | | 600 | | 270| | 1270   |
| 1961| |       | | 200 | | 200 | | 1935| | 420| | 2755   |
| 1962| |       | | 200 | | 2025| | 2520| | 495| | 5240   |
| 1963| | 2500  | | 45  | | 2880| | 4290| | 125| | 7340   |
| 1964| | 12000 | | 180 | | 3465| | 4750| | 240| | 8615   |
| 1965| | 3200  | | 83  | | 7000| | 2080| | 180| | 9343   |
| 1966| | 1000  | | 625 | | 1680| | 1560| | 120| | 3985   |
| 1967| | 1200  | | 40  | | 1260| | 1040| | 240| | 2480   |
| 1968| | 2500  | | 30  | | 840 | | 2080| | 180| | 3130   |
| 1969| | 3500  | | 20  | | 1680| | 1560| | 120| | 3380   |
| 1970| | 2000  | |	40  | | 1260| |	1040| |    | |	      |
| 1971| | 1600  | |	30  | | 840 | |	    | |    | |        |
| 1972| |  900  | |	20  | |     | |	    |	|    | |        |
|1973 | |2000   | |  | |  | |	 | |  | |	   |
|1974 | |1600   | |  | | | |	 | |  | |    |
|1975 | |900    | |  | |  | |	 | |  | |    |
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|
---
Model input data 

| b.Year | |Spawner| |b.Age3 | |b.Age4 | |b.Age5 | |b.Age6 | |Recruit| 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|
| 1963| | 2500  | | 45  | | 2880| | 4290| | 125| | 7340   |
| 1964| | 12000 | | 180 | | 3465| | 4750| | 240| | 8615   |
| 1965| | 3200  | | 83  | | 7000| | 2080| | 180| | 9343   |
| 1966| | 1000  | | 625 | | 1680| | 1560| | 120| | 3985   |
| 1967| | 1200  | | 40  | | 1260| | 1040| | 240| | 2480   |
| 1968| | 2500  | | 30  | | 840 | | 2080| | 180| | 3130   |
| 1969| | 3500  | | 20  | | 1680| | 1560| | 120| | 3380   |
|______|_|_______|_|_______|_|______|_|______|_|______|_|______|





