# Missing data handling 

Missing data in Run data type has multiple sources: 
* Run,Escapement,or Harvest data are missing 
* Run age composition data are missing. 

In either case, this will affect construction of a brood table of multiple years. 

In the following example, missing age data or Run data of 1995 will result in loosing recruit data of of 1989, 1990, and 1991. 

**Missing 1995 age data** 

| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000   | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000   | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000   | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000 | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000   | |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375    | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |1125    | |10000  | |  | |	 | |  | 
|1996  | |1000    | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000    | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|

**Missing 1995 age data** 

| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000   | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000   | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000   | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000 | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000   | |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375    | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |1125    | |  | | 0.23 | |0.76	 | | 0.01 | 
|1996  | |1000    | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000    | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|


**Resulting brood table**  
Brood table of 1989,1990, and 1991 data will be deleted. 

| b.Year | |Spawner| |b.Age4 | |b.Age5 | |b.Age6 | |Recruit | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|
| 1988| | 2500    | | 1946    | |3005     | | 0    | | 4951| 
| 1989| | 15000   | | 55896 | |6800 | | | |  | 
| 1990| | 14000   | | 673   | | | | 54| | | 
| 1991| | 2000    | |    | | 2795 | | 0| | | 
| 1992| | 5000    | | 2526 | | 6105| | 78| | 8709| 
| 1993| | 12000   | | 40855  | | 6275| | 4823| | 51953| 
| 1994| | 2375  | | 1569 | | 9110| | 75| | 10754| 
| 1995| | 1125  | | 39118  | | 1411| | 94| |40623    | 
| 1996| | 1000  | | 395  | | 1081 | | 670  | |2146  | 
|______|_|_______|_|_______|_|______|_|______|_|______|
---

**Missing 1995 Spawner and Run data** 

| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000   | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000   | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000   | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000 | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000   | |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375    | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |    | |  | | 0.23 | |0.76	 | | 0.01 | 
|1996  | |1000    | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000    | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
--

  
**Missing 1995 data completely**  


| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000 | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000 | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000  | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000 | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000| |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375 | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |     | |      | |      | |	    | |  | 
|1996  | |1000 | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000  | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
  
**Resulting brood table**  
Brood table of 1989,1990,1991,and 1995 data will be deleted. 

| b.Year | |Spawner| |b.Age4 | |b.Age5 | |b.Age6 | |Recruit | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|
| 1988| | 2500    | | 1946    | |3005     | | 0    | | 4951| 
| 1989| | 15000   | | 55896 | |6800 | | | |  | 
| 1990| | 14000   | | 673   | | | | 54| | | 
| 1991| | 2000    | |    | | 2795 | | 0| | | 
| 1992| | 5000    | | 2526 | | 6105| | 78| | 8709| 
| 1993| | 12000   | | 40855  | | 6275| | 4823| | 51953| 
| 1994| | 2375  | | 1569 | | 9110| | 75| | 10754| 
| 1995| |   | | 39118  | | 1411| | 94| |40623    | 
| 1996| | 1000  | | 395  | | 1081 | | 670  | |2146  | 
|______|_|_______|_|_______|_|______|_|______|_|______|


**Missing 1995 Escapement/Spawner data**

| Year | |  Spawner| | Run    | | A4  | |  A5 | | A6  |
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|_____|_|_______|_|______|_|_____|_|_____|_|_____|
|1988  | |2500  | |7293  | | 0.25 | | 0.60 | | 0.15 |
|1989  | |15000 | |65621  | | 0.91 | | 0.09 | | 0.00 | 
|1990  | |14000 | |39516  | | 0.07 | | 0.92 | | 0.01 | 
|1991  | |2000  | |6769 | | 0.16 | | 0.83 | | 0.01 |
|1992  | |5000  | |16213  | | 0.12 | |	0.77 | | 0.11 | 
|1993  | |12000 | |60103  | | 0.93 | |	0.05 | | 0.02 | 
|1994  | |2375  | |7473  | | 0.09 | |	0.91 | | 0.00 | 
|1995  | |       | | 10000 | | 0.23 | |0.76| | 0.01 | 
|1996  | |1000    | |5374  | | 0.47 | |	0.52 | | 0.01 | 
|1997  | |9000    | |46960  | | 0.87 | |	0.13 | | 0.00 | 
|_____|_|_______|_|______|_|_____|_|_____|_|_____|_|_____|
  
**Resulting brood table**  
Brood table of1995 data will be deleted. 

| b.Year | |Spawner| |b.Age4 | |b.Age5 | |b.Age6 | |Recruit | 
|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|---:|-------:|
|______|_|_______|_|_______|_|______|_|______|_|______|
| 1988| | 2500    | | 1946    | |3005     | | 0    | | 4951| 
| 1989| | 15000   | | 55896 | |6800 | | 100| | 62796  | 
| 1990| | 14000   | | 673   | |7600 | | 54| |8327 | 
| 1991| | 2000    | | 2300   | | 2795 | | 0| | 5095| 
| 1992| | 5000    | | 2526 | | 6105| | 78| | 8709| 
| 1993| | 12000   | | 40855  | | 6275| | 4823| | 51953| 
| 1994| | 2375  | | 1569 | | 9110| | 75| | 10754| 
| 1995| |   | | 39118  | | 1411| | 94| | 40623  | 
| 1996| | 1000  | | 395  | | 1081 | | 670  | |2146  | 
|______|_|_______|_|_______|_|______|_|______|_|______|

 


